#ifndef __POUS_H
#define __POUS_H

#include "accessor.h"
#include "iec_std_lib.h"

// PROGRAM PLC2
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_LOCATED(INT,COLORSENSOR_RED)
  __DECLARE_LOCATED(INT,COLORSENSOR_GREEN)
  __DECLARE_LOCATED(INT,COLORSENSOR_BLUE)
  __DECLARE_LOCATED(INT,RANGESENSOR)
  __DECLARE_LOCATED(BOOL,PUMP)
  __DECLARE_LOCATED(BOOL,DOSER_RED)
  __DECLARE_LOCATED(BOOL,DOSER_BLUE)
  __DECLARE_VAR(TIME,SETTLETIME)
  __DECLARE_VAR(TIME,DOSETIME)
  __DECLARE_LOCATED(BOOL,TREATMENTCOMPLETE)
  __DECLARE_LOCATED(INT,STAGE)
  __DECLARE_VAR(REAL,DESIREDDISTANCEFILL)
  __DECLARE_LOCATED(REAL,MEASUREDDISTANCE)
  __DECLARE_VAR(INT,MINRED)
  TON DOSERREDTIMER;
  TON DOSERBLUETIMER;
  TON SETTLETIMER;
  __DECLARE_LOCATED(BOOL,DOSETIMERDONE)
  __DECLARE_VAR(BOOL,SETTLEEN)

} PLC2;

void PLC2_init__(PLC2 *data__, BOOL retain);
// Code part
void PLC2_body__(PLC2 *data__);
#endif //__POUS_H
